@startuml
'https://plantuml.com/class-diagram

class CloudApplication
class E2ETest
class Express
class ExpressApplication
class Http
class HttpServer
class MongoDB
class MongoAtlas
class MongoInMemory

ExpressApplication o-- Express
HttpServer o-- Http

MongoAtlas o-- MongoDB
MongoInMemory o-- MongoDB

CloudApplication o-- ExpressApplication
CloudApplication o-- HttpServer
CloudApplication o-- MongoAtlas

E2ETest o-- ExpressApplication
E2ETest o-- HttpServer
E2ETest o-- MongoInMemory
@enduml